---
# tasks file for donfilemon.ntp
- name: Stop and disable Chronyd
  service:
    name: chronyd
    state: stopped
    enabled: no
  ignore_errors: yes
- name: install the NTP
  yum:
    name: ntp
    state: present
- name: Add ntp configuration
  template: 
    src: ntp.conf.j2 
    dest: /etc/ntp.conf
    backup: yes
  register: conf
- name: Start service ntpd if not started and enable autostart 
  service:
    name: ntpd
    state: started
    enabled: yes
- name: Restart service ntpd, in all cases
  service:
    name: ntpd
    state: restarted
  when: conf.changed



