---
# tasks file for donfilemon.ntp
- name: install the NTP
  yum:
    name: ntp
    state: present
- name: Add ntp configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
    backup: yes
    register: conf
- name: Start service ntpd if not started and enable autostart (FOR CentOS 6 and RedHat 6)
  service:
    name: ntpd
    state: started
    enabled: yes
- name: Restart service ntpd, in all cases
  service:
    name: ntpd
    state: restarted
  when: conf.changed



