- name: Depoly ntp
  hosts: test
  become: true
  gather_facts: yes
# Roles  
  roles:
    - donfilemon.ntp
  vars:
    # vars for donfilemon.ntp
    network_addr: 192.168.227.0
    mask_addr: 255.255.255.0

    ntp_servers:
      - "0.pl.pool.ntp.org iburst"
      - "1.pl.pool.ntp.org iburst"
      - "2.pl.pool.ntp.org iburst"
      - "3.pl.pool.ntp.org iburst"